name: Upload Python Package

on:
  push:
    tags:
      - "*"

jobs:
  pure-python-wheel-publish:
    name: Pure Python Wheel Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install deps
      run: python -m pip install wheel==0.42.0 twine==4.0.2
    - name: Build pure python wheel
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      run: pip wheel -w wheelhouse .
    - name: Publish
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --skip-existing wheelhouse/*
